name: Actions
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
    steps:
      - name: Builder
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: StandaloneWindows64

      # Return License
      - name: Return license
        uses: game-ci/unity-return-license@v2
        if: always()
